import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

//Components
import HeaderScript from "./component/header_script";
import Header from "./component/header";
import FooterScript from "./component/footer_script";
import Footer from "./component/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <HeaderScript />
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
        <FooterScript />
      </body>
    </html>
  );
}
